services:
  nginx:
    image: nginx:alpine3.23
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend

  frontend:
    image: europe-central2-docker.pkg.dev/smart-altar-496311-p4/sgame-images/sgame-frontend:latest
    depends_on:
      - backend
    environment:
      PORT: 80
      BACKEND_HOST: backend

  backend:
    image: europe-central2-docker.pkg.dev/smart-altar-496311-p4/sgame-images/sgame-backend:latest
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      APP_ENV: production
      HOST: 0.0.0.0
      PORT: 80
      MONGO_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_NAME: ${MONGO_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: 0
      STORAGE_PROVIDER: gcs
      BUCKET_NAME: sgame-bucket
      GOOGLE_APPLICATION_CREDENTIALS: /app/smart-altar-496311-p4-5cf9bc5fd4e7.json
      FRONTEND_URL: https://sgame.sgame.dedyn.io
      USER_AGENT: "SGame/1.0"
    volumes:
      - ./smart-altar-496311-p4-5cf9bc5fd4e7.json:/app/smart-altar-496311-p4-5cf9bc5fd4e7.json

  mongodb:
    image: mongo:6.0
    init: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_NAME}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    healthcheck:
      test:
        ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis/redis-stack-server:7.4.0-v8
    ports:
      - 6379:6379
    environment:
      REDIS_ARGS: "--user ${REDIS_USERNAME} allcommands allkeys allchannels on >${REDIS_PASSWORD} --notify-keyspace-events Ex"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  mongodb_data_container:
