FROM golang:1.25-alpine

WORKDIR /app

RUN apk add --no-cache ffmpeg build-base git ca-certificates
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 80

CMD ["air"]
