// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/holdennekt/sgame/backend/internal/eventsprocessor"
	redis2 "github.com/holdennekt/sgame/backend/internal/infrastructure/cache/redis"
	mongo2 "github.com/holdennekt/sgame/backend/internal/infrastructure/database/mongo"
	"github.com/holdennekt/sgame/backend/internal/infrastructure/realtime/pubsub"
	"github.com/holdennekt/sgame/backend/internal/infrastructure/realtime/streams"
	"github.com/holdennekt/sgame/backend/internal/interface/cache"
	"github.com/holdennekt/sgame/backend/internal/interface/realtime"
	"github.com/holdennekt/sgame/backend/internal/interface/repository"
	"github.com/holdennekt/sgame/backend/internal/interface/storage"
	"github.com/holdennekt/sgame/backend/internal/service"
	"github.com/holdennekt/sgame/backend/internal/transport/http"
	"github.com/holdennekt/sgame/backend/internal/transport/ws"
	"github.com/redis/go-redis/v9"
	"go.mongodb.org/mongo-driver/mongo"
)

import (
	_ "github.com/holdennekt/sgame/backend/docs"
)

// Injectors from wire.go:

func InitializeApp(mdb *mongo.Database, rds *redis.Client, storage2 storage.Storage) *app {
	room := redis2.NewRoomCache(rds)
	session := redis2.NewSessionCache(rds)
	user := mongo2.NewUserRepository(mdb)
	authService := service.NewAuthService(session, user)
	authController := http.NewAuthController(authService)
	userService := service.NewUserService(user)
	userController := http.NewUserController(userService)
	pack := mongo2.NewPackRepository(mdb)
	packService := service.NewPackService(user, pack, storage2)
	packController := http.NewPackController(packService)
	repositoryRoom := mongo2.NewRoomRepository(mdb)
	pubSubChannelGetter := providePubSubChannelGetter(rds)
	streamsChannelGetter := provideStreamsChannelGetter(rds)
	roomInternalEventsProcessorGetter := provideRoomInternalEventsProcessorGetter(room, repositoryRoom, pack, storage2, pubSubChannelGetter, streamsChannelGetter)
	roomService := provideRoomService(user, pack, repositoryRoom, room, pubSubChannelGetter, streamsChannelGetter, roomInternalEventsProcessorGetter)
	roomController := http.NewRoomController(room, repositoryRoom, packService, roomService)
	lobbyEventsProcessorGetter := provideLobbyEventsProcessorGetter(room, pubSubChannelGetter)
	lobbyHandler := provideLobbyHandler(userService, pubSubChannelGetter, lobbyEventsProcessorGetter)
	roomEventsProcessorGetter := provideRoomEventsProcessorGetter(room, repositoryRoom, pack, storage2, pubSubChannelGetter, streamsChannelGetter)
	roomHandler := provideRoomHandler(roomService, userService, roomEventsProcessorGetter, pubSubChannelGetter, streamsChannelGetter)
	appApp := NewApp(room, authController, userController, packController, roomController, lobbyHandler, roomHandler, roomInternalEventsProcessorGetter)
	return appApp
}

// wire.go:

var RepoSet = wire.NewSet(mongo2.NewUserRepository, mongo2.NewRoomRepository, mongo2.NewPackRepository)

var CacheSet = wire.NewSet(redis2.NewSessionCache, redis2.NewRoomCache)

type PubSubChannelGetter struct {
	realtime.ServerChannelGetter
}

type StreamsChannelGetter struct {
	realtime.ServerChannelGetter
}

func providePubSubChannelGetter(client *redis.Client) PubSubChannelGetter {
	return PubSubChannelGetter{pubsub.NewServerChannelGetter(client)}
}

func provideStreamsChannelGetter(client *redis.Client) StreamsChannelGetter {
	return StreamsChannelGetter{streams.NewServerChannelGetter(client)}
}

func provideLobbyEventsProcessorGetter(roomCache cache.Room, pubsubGetter PubSubChannelGetter) eventsprocessor.LobbyEventsProcessorGetter {
	return eventsprocessor.NewLobbyEventsProcessorGetter(pubsubGetter.ServerChannelGetter, roomCache)
}

func provideRoomEventsProcessorGetter(roomCache cache.Room, roomRepo repository.Room, packRepo repository.Pack, storage2 storage.Storage, pubsubGetter PubSubChannelGetter, streamsGetter StreamsChannelGetter) eventsprocessor.RoomEventsProcessorGetter {
	return eventsprocessor.NewRoomEventsProcessorGetter(pubsubGetter.ServerChannelGetter, streamsGetter.ServerChannelGetter, streamsGetter.ServerChannelGetter, roomCache, roomRepo, packRepo, storage2)
}

func provideRoomInternalEventsProcessorGetter(roomCache cache.Room, roomRepo repository.Room, packRepo repository.Pack, storage2 storage.Storage, pubsubGetter PubSubChannelGetter, streamsGetter StreamsChannelGetter) eventsprocessor.RoomInternalEventsProcessorGetter {
	return eventsprocessor.NewRoomInternalEventsProcessorGetter(pubsubGetter.ServerChannelGetter, streamsGetter.ServerChannelGetter, streamsGetter.ServerChannelGetter, roomCache, roomRepo, packRepo, storage2)
}

func provideRoomService(userRepository repository.User, packRepository repository.Pack, roomRepository repository.Room, roomCache cache.Room, pubsubGetter PubSubChannelGetter, streamsGetter StreamsChannelGetter, roomInternalEventsProcessorGetter eventsprocessor.RoomInternalEventsProcessorGetter) *service.RoomService {
	return service.NewRoomService(userRepository, packRepository, roomRepository, roomCache, pubsubGetter.ServerChannelGetter, streamsGetter.ServerChannelGetter, streamsGetter.ServerChannelGetter, roomInternalEventsProcessorGetter)
}

var ServiceSet = wire.NewSet(service.NewAuthService, service.NewUserService, provideRoomService, service.NewPackService)

var ControllerSet = wire.NewSet(http.NewAuthController, http.NewUserController, http.NewPackController, http.NewRoomController)

func provideLobbyHandler(userService *service.UserService, pubsubGetter PubSubChannelGetter, lobbyEventsProcessorGetter eventsprocessor.LobbyEventsProcessorGetter) *ws.LobbyHandler {
	return ws.NewLobbyHandler(userService, pubsubGetter.ServerChannelGetter, lobbyEventsProcessorGetter)
}

func provideRoomHandler(roomService *service.RoomService, userService *service.UserService, roomEventsProcessorGetter eventsprocessor.RoomEventsProcessorGetter, pubsubGetter PubSubChannelGetter, streamsGetter StreamsChannelGetter) *ws.RoomHandler {
	return ws.NewRoomHandler(roomService, userService, pubsubGetter.ServerChannelGetter, streamsGetter.ServerChannelGetter, streamsGetter.ServerChannelGetter, roomEventsProcessorGetter)
}

var HandlerSet = wire.NewSet(
	provideLobbyHandler,
	provideRoomHandler,
)
