// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/google/wire"
	"github.com/holdennekt/sgame/backend/internal/config"
	"github.com/holdennekt/sgame/backend/internal/eventsprocessor"
	redis2 "github.com/holdennekt/sgame/backend/internal/infrastructure/cache/redis"
	mongo2 "github.com/holdennekt/sgame/backend/internal/infrastructure/database/mongo"
	"github.com/holdennekt/sgame/backend/internal/infrastructure/realtime/pubsub"
	"github.com/holdennekt/sgame/backend/internal/infrastructure/realtime/streams"
	validator2 "github.com/holdennekt/sgame/backend/internal/infrastructure/validator"
	"github.com/holdennekt/sgame/backend/internal/interface/cache"
	"github.com/holdennekt/sgame/backend/internal/interface/realtime"
	"github.com/holdennekt/sgame/backend/internal/interface/repository"
	"github.com/holdennekt/sgame/backend/internal/interface/storage"
	"github.com/holdennekt/sgame/backend/internal/interface/validator"
	"github.com/holdennekt/sgame/backend/internal/service"
	"github.com/holdennekt/sgame/backend/internal/transport/http"
	"github.com/holdennekt/sgame/backend/internal/transport/ws"
	"github.com/redis/go-redis/v9"
	"go.mongodb.org/mongo-driver/mongo"
)

import (
	_ "github.com/holdennekt/sgame/backend/docs"
)

// Injectors from wire.go:

func InitializeApp(mdb *mongo.Database, rds *redis.Client, storage2 storage.Storage, cfg *config.Config) *app {
	room := redis2.NewRoomCache(rds)
	session := redis2.NewSessionCache(rds)
	user := mongo2.NewUserRepository(mdb)
	authService := service.NewAuthService(session, user)
	authController := http.NewAuthController(authService)
	userService := service.NewUserService(user, session)
	userController := http.NewUserController(userService)
	pack := mongo2.NewPackRepository(mdb)
	packDraft := mongo2.NewPackDraftRepository(mdb)
	attachmentService := service.NewAttachmentService(storage2)
	packService := service.NewPackService(pack, packDraft, storage2, attachmentService)
	packController := http.NewPackController(packService)
	packDraftService := service.NewPackDraftService(packDraft, pack, storage2, attachmentService, packService)
	packDraftController := http.NewPackDraftController(packDraftService)
	repositoryRoom := mongo2.NewRoomRepository(mdb)
	manager := provideManager(rds)
	pubSubChannelGetter := providePubSubChannelGetter(rds, manager)
	streamsChannelGetter := provideStreamsChannelGetter(rds, manager)
	streamsPersistentChannelGetter := provideStreamsPersistentChannelGetter(rds, manager)
	roomInternalEventsProcessorGetter := provideRoomInternalEventsProcessorGetter(room, repositoryRoom, pack, storage2, pubSubChannelGetter, streamsChannelGetter, streamsPersistentChannelGetter, cfg)
	answerValidator := provideAnswerValidator(cfg)
	roomService := provideRoomService(pack, repositoryRoom, room, pubSubChannelGetter, streamsChannelGetter, streamsPersistentChannelGetter, roomInternalEventsProcessorGetter, cfg, answerValidator)
	roomController := http.NewRoomController(packService, roomService)
	lobbyEventsProcessorGetter := provideLobbyEventsProcessorGetter(room, pubSubChannelGetter)
	lobbyHandler := provideLobbyHandler(pubSubChannelGetter, lobbyEventsProcessorGetter)
	roomEventsProcessorGetter := provideRoomEventsProcessorGetter(room, repositoryRoom, pack, storage2, pubSubChannelGetter, streamsChannelGetter, streamsPersistentChannelGetter, cfg, answerValidator, roomService)
	roomHandler := provideRoomHandler(roomService, roomEventsProcessorGetter, pubSubChannelGetter, streamsChannelGetter, streamsPersistentChannelGetter)
	appApp := NewApp(cfg, room, authController, userController, packController, packDraftController, roomController, lobbyHandler, roomHandler, roomInternalEventsProcessorGetter)
	return appApp
}

// wire.go:

var RepoSet = wire.NewSet(mongo2.NewUserRepository, mongo2.NewRoomRepository, mongo2.NewPackRepository, mongo2.NewPackDraftRepository)

var CacheSet = wire.NewSet(redis2.NewSessionCache, redis2.NewRoomCache)

type PubSubChannelGetter struct {
	realtime.ChannelGetter
}

type StreamsChannelGetter struct {
	realtime.ChannelGetter
}

type StreamsPersistentChannelGetter struct {
	realtime.ChannelGetter
}

func provideManager(client *redis.Client) *pubsub.Manager {
	return pubsub.NewManager(client)
}

func providePubSubChannelGetter(client *redis.Client, manager *pubsub.Manager) PubSubChannelGetter {
	return PubSubChannelGetter{pubsub.NewManagedChannelGetter(client, manager)}
}

func provideStreamsChannelGetter(client *redis.Client, manager *pubsub.Manager) StreamsChannelGetter {
	return StreamsChannelGetter{streams.NewManagedChannelGetter(client, manager)}
}

func provideStreamsPersistentChannelGetter(client *redis.Client, manager *pubsub.Manager) StreamsPersistentChannelGetter {
	return StreamsPersistentChannelGetter{streams.NewPersistentManagedChannelGetter(client, manager)}
}

func provideLobbyEventsProcessorGetter(roomCache cache.Room, pubsubGetter PubSubChannelGetter) eventsprocessor.LobbyEventsProcessorGetter {
	return eventsprocessor.NewLobbyEventsProcessorGetter(pubsubGetter.ChannelGetter, roomCache)
}

func provideAnswerValidator(cfg *config.Config) validator.AnswerValidator {
	switch cfg.ValidatorType {
	case "ollama":
		return validator2.NewLocalEmbeddingValidator(cfg.OllamaURL, cfg.OllamaThreshold)
	case "gemini":
		v, err := validator2.NewGeminiValidator(context.Background(), cfg.GeminiProjectID, cfg.GeminiLocation, cfg.GeminiSystemPrompt)
		if err != nil {
			panic("failed to initialize Gemini validator: " + err.Error())
		}
		return v
	default:
		return nil
	}
}

func provideRoomEventsProcessorGetter(roomCache cache.Room, roomRepo repository.Room, packRepo repository.Pack, storage2 storage.Storage, pubsubGetter PubSubChannelGetter, streamsGetter StreamsChannelGetter, persistentGetter StreamsPersistentChannelGetter, cfg *config.Config, validator3 validator.AnswerValidator, roomService *service.RoomService) eventsprocessor.RoomEventsProcessorGetter {
	return eventsprocessor.NewRoomEventsProcessorGetter(pubsubGetter.ChannelGetter, streamsGetter.ChannelGetter, persistentGetter.ChannelGetter, roomCache, roomRepo, packRepo, storage2, cfg, validator3, roomService.Disconnect)
}

func provideRoomInternalEventsProcessorGetter(roomCache cache.Room, roomRepo repository.Room, packRepo repository.Pack, storage2 storage.Storage, pubsubGetter PubSubChannelGetter, streamsGetter StreamsChannelGetter, persistentGetter StreamsPersistentChannelGetter, cfg *config.Config) eventsprocessor.RoomInternalEventsProcessorGetter {
	return eventsprocessor.NewRoomInternalEventsProcessorGetter(pubsubGetter.ChannelGetter, streamsGetter.ChannelGetter, persistentGetter.ChannelGetter, roomCache, roomRepo, packRepo, storage2, cfg)
}

func provideRoomService(packRepository repository.Pack, roomRepository repository.Room, roomCache cache.Room, pubsubGetter PubSubChannelGetter, streamsGetter StreamsChannelGetter, persistentGetter StreamsPersistentChannelGetter, roomInternalEventsProcessorGetter eventsprocessor.RoomInternalEventsProcessorGetter, cfg *config.Config, validator3 validator.AnswerValidator) *service.RoomService {
	return service.NewRoomService(packRepository, roomRepository, roomCache, pubsubGetter.ChannelGetter, streamsGetter.ChannelGetter, persistentGetter.ChannelGetter, roomInternalEventsProcessorGetter, cfg, validator3)
}

var ServiceSet = wire.NewSet(service.NewAuthService, service.NewUserService, provideRoomService, service.NewAttachmentService, service.NewPackService, service.NewPackDraftService)

var ControllerSet = wire.NewSet(http.NewAuthController, http.NewUserController, http.NewPackController, http.NewPackDraftController, http.NewRoomController)

func provideLobbyHandler(pubsubGetter PubSubChannelGetter, lobbyEventsProcessorGetter eventsprocessor.LobbyEventsProcessorGetter) *ws.LobbyHandler {
	return ws.NewLobbyHandler(pubsubGetter.ChannelGetter, lobbyEventsProcessorGetter)
}

func provideRoomHandler(roomService *service.RoomService, roomEventsProcessorGetter eventsprocessor.RoomEventsProcessorGetter, pubsubGetter PubSubChannelGetter, streamsGetter StreamsChannelGetter, persistentGetter StreamsPersistentChannelGetter) *ws.RoomHandler {
	return ws.NewRoomHandler(roomService, pubsubGetter.ChannelGetter, streamsGetter.ChannelGetter, persistentGetter.ChannelGetter, roomEventsProcessorGetter)
}

var HandlerSet = wire.NewSet(
	provideLobbyHandler,
	provideRoomHandler,
)
