// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	redis2 "github.com/holdennekt/sgame/internal/infrastructure/cache/redis"
	mongo2 "github.com/holdennekt/sgame/internal/infrastructure/database/mongo"
	"github.com/holdennekt/sgame/internal/infrastructure/realtime/pubsub"
	"github.com/holdennekt/sgame/internal/interface/cache"
	"github.com/holdennekt/sgame/internal/interface/realtime"
	"github.com/holdennekt/sgame/internal/interface/repository"
	"github.com/holdennekt/sgame/internal/service"
	"github.com/holdennekt/sgame/internal/transport/http"
	"github.com/holdennekt/sgame/internal/transport/ws"
	"github.com/redis/go-redis/v9"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeAuthController(mdb *mongo.Database, rds *redis.Client) *http.AuthController {
	sessionCache := redis2.NewSessionCache(rds)
	userRepository := mongo2.NewUserRepository(mdb)
	authService := service.NewAuthService(sessionCache, userRepository)
	authController := http.NewAuthController(authService)
	return authController
}

func InitializeUserController(mdb *mongo.Database) *http.UserController {
	userRepository := mongo2.NewUserRepository(mdb)
	userService := service.NewUserService(userRepository)
	userController := http.NewUserController(userService)
	return userController
}

func InitializePackController(mdb *mongo.Database) *http.PackController {
	userRepository := mongo2.NewUserRepository(mdb)
	packRepository := mongo2.NewPackRepository(mdb)
	packService := service.NewPackService(userRepository, packRepository)
	packController := http.NewPackController(packService)
	return packController
}

func InitializeRoomController(mdb *mongo.Database, rds *redis.Client) *http.RoomController {
	serverChannelGetter := pubsub.NewServerChannelGetter(rds)
	roomCache := redis2.NewRoomCache(rds)
	roomRepository := mongo2.NewRoomRepository(mdb)
	userRepository := mongo2.NewUserRepository(mdb)
	packRepository := mongo2.NewPackRepository(mdb)
	packService := service.NewPackService(userRepository, packRepository)
	roomService := service.NewRoomService(serverChannelGetter, roomCache, userRepository, packRepository, roomRepository)
	roomController := http.NewRoomController(serverChannelGetter, roomCache, roomRepository, packService, roomService)
	return roomController
}

func InitializeLobbyHandler(mdb *mongo.Database, rds *redis.Client) *ws.LobbyHandler {
	serverChannelGetter := pubsub.NewServerChannelGetter(rds)
	roomCache := redis2.NewRoomCache(rds)
	userRepository := mongo2.NewUserRepository(mdb)
	userService := service.NewUserService(userRepository)
	lobbyHandler := ws.NewLobbyHandler(serverChannelGetter, roomCache, userService)
	return lobbyHandler
}

func InitializeRoomHandler(mdb *mongo.Database, rds *redis.Client) *ws.RoomHandler {
	serverChannelGetter := pubsub.NewServerChannelGetter(rds)
	roomCache := redis2.NewRoomCache(rds)
	roomRepository := mongo2.NewRoomRepository(mdb)
	userRepository := mongo2.NewUserRepository(mdb)
	userService := service.NewUserService(userRepository)
	packRepository := mongo2.NewPackRepository(mdb)
	packService := service.NewPackService(userRepository, packRepository)
	roomService := service.NewRoomService(serverChannelGetter, roomCache, userRepository, packRepository, roomRepository)
	roomHandler := ws.NewRoomHandler(serverChannelGetter, roomCache, roomRepository, userService, packService, roomService)
	return roomHandler
}

// wire.go:

var UserRepoSet = wire.NewSet(mongo2.NewUserRepository, wire.Bind(new(repository.User), new(*mongo2.UserRepository)))

var PackRepoSet = wire.NewSet(mongo2.NewPackRepository, wire.Bind(new(repository.Pack), new(*mongo2.PackRepository)))

var RoomRepoSet = wire.NewSet(mongo2.NewRoomRepository, wire.Bind(new(repository.Room), new(*mongo2.RoomRepository)))

var SessionCacheSet = wire.NewSet(redis2.NewSessionCache, wire.Bind(new(cache.Session), new(*redis2.SessionCache)))

var RoomCacheSet = wire.NewSet(redis2.NewRoomCache, wire.Bind(new(cache.Room), new(*redis2.RoomCache)))

var ServerChannelGetterSet = wire.NewSet(pubsub.NewServerChannelGetter, wire.Bind(new(realtime.ServerChannelGetter), new(*pubsub.ServerChannelGetter)))
